services:
  couchdb:
    expose:
      - 5984
    image: treehouses/couchdb:2.3.1
    ports:
      - "2200:5984"
    volumes:
      - "/srv/planet/conf:/opt/couchdb/etc/local.d"
      - "/srv/planet/data:/opt/couchdb/data"
      - "/srv/planet/log:/opt/couchdb/var/log"
  chatapi:
    image: treehouses/planet:chatapi
    depends_on:
      - couchdb
    ports:
      - "5000:5000"
    environment:
      - COUCHDB_HOST=http://couchdb:5984
      - SERVE_PORT=5000
    env_file:
      - .chat.env
  db-init:
    image: treehouses/planet:db-init
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
      - COUCHDB_USER=admin
      - COUCHDB_PASS=admin
